$(document).ready(function () {

    var rawdata;
    //var language = require('datatables.net-plugins/i18n/th.js');
    // table data
    var table = $('#job_table').DataTable({
        //language: language,
        "ajax": "data/job.php?skey=" + skey + "&range=1m",
        responsive: true,
        dom: 'BPlfrtip',
        searchPanes: {
            initCollapsed: true,
        },
        buttons: [
            {
                text: 'export excel',
                extend: 'excel',
            },
            {
                extend: 'csv',
                text: 'export csv',
                charset: 'utf-8',
                extension: '.csv',
                fieldSeparator: ',',
                fieldBoundary: '',
                filename: 'export',
                bom: true
            },
            {
                text: 'export pdf',
                extend: 'pdf',
                customize: function (doc) {
                    processDoc(doc);
                    // Data URL generated by http://dataurl.net/#dataurlmaker
                }
            },
            {
                extend: 'collection',
                text: 'ระยะเวลาย้อนหลัง',
                autoClose: true,
                buttons: [{
                        text: '1 เดือนล่าสุด',
                        action: function (e, dt, node, config) {
                            dt.ajax.url("data/job.php?skey=" + skey + "&range=1m").load();
                        }
                    },
                    {
                        text: '3 เดือนล่าสุด',
                        action: function (e, dt, node, config) {
                            dt.ajax.url("data/job.php?skey=" + skey + "&range=3m").load();
                        }
                    },
                    {
                        text: '6 เดือนล่าสุด',
                        action: function (e, dt, node, config) {
                            dt.ajax.url("data/job.php?skey=" + skey + "&range=6m").load();
                        }
                    },
                    {
                        text: '1 ปีล่าสุด',
                        action: function (e, dt, node, config) {
                            dt.ajax.url("data/job.php?skey=" + skey + "&range=1y").load();
                        }
                    },
                    {
                        text: '2 ปีล่าสุด',
                        action: function (e, dt, node, config) {
                            dt.ajax.url("data/job.php?skey=" + skey + "&range=2y").load();
                        }
                    },
                    {
                        text: 'ทั้งหมด',
                        action: function (e, dt, node, config) {
                            dt.ajax.url("data/job.php?skey=" + skey + "").load();
                        }
                    }
                ]
            },
        ],
//            $data[] = [$job['id'], $job['job_role_id'], $job['patient_id'], $job['patient_number'], $job['user_id'], $job['pre_name'], $job['name'], $job['lastname'], $job['jobname'], $job['pay'], $job['cost_count_per_day'], $job['comment'], $job['finish_date'], $job['insert_time'], $job['qty'], $job['req_date']];
//----------------------------0------------------1-----------------2---------------------3--------------------4---------------5----------------6---------------7----------------8--------------9-------------------10---------------------11----------------12--------------------13---------------14-------------15----------
        columnDefs: [
            {
                "render": function (data, type, row) {
                    let html = '<a href="job_edit.php?id=' + row[0] + '" class="" target="_blank">' + row[0] + '</a>';
                    return html;
                },
                "targets": 0
            },
            {
                "render": function (data, type, row) {
                    let html = '<a href="patient_edit.php?id=' + row[2] + '">' + row[3] + '</a>';

                    return html;
                },
                "targets": 3
            },
            {
                "render": function (data, type, row) {
                    return row[15];
                },
                "targets": 12
            },
            {
                "render": function (data, type, row) {
                    return row[12];
                },
                "targets": 13
            },
            {
                visible: false,
                targets: []
            },
        ],
    });

    table.on('draw', function () {
        // console.log(table.rows().data());
        rawdata = table.rows().data();
        // console.log(rawdata.length);
    });

    $("#csvdownload").click(function () {
        var data = [
            ["id", "job_role_id", "patient_id", "patient_number", "user_id", "pre_name", "name", "lastname", "jobname", "pay", "cost_count_per_day", "comment", "finish_date", "insert_time"]
        ];

        // console.log(label_history.length);return;

        for (var count = 0; count < rawdata.length; count++) {
            data.push(rawdata[count]);
        }

        let csvContent = data.map(e => e.join(",")).join("\n");

        var encodedUri = encodeURIComponent("\uFEFF" + csvContent);
        var link = document.createElement("a");
        link.setAttribute('href', 'data:text/csv; charset=utf-8,' + encodedUri);
        link.setAttribute("download", "jobdata_" + rawdata[rawdata.length - 1][13] + "_to_" + rawdata[0][13] + ".csv");
        document.body.appendChild(link);
        link.click();
    });

    function processDoc(doc) {
        //
        // https://pdfmake.github.io/docs/fonts/custom-fonts-client-side/
        //
        // Update pdfmake's global font list, using the fonts available in
        // the customized vfs_fonts.js file (do NOT remove the Roboto default):
        pdfMake.fonts = {
            Roboto: {
                normal: 'Roboto-Regular.ttf',
                bold: 'Roboto-Medium.ttf',
                italics: 'Roboto-Italic.ttf',
                bolditalics: 'Roboto-MediumItalic.ttf'
            },
            angsa : {
                normal: domain+'/fonts/angsau.ttf',
                bold: domain+'/fonts/angsaub.ttf',
                italics: domain+'/fonts/angsaui.ttf',
                bolditalics: domain+'/fonts/angsauz.ttf',
            }
        };
        // modify the PDF to use a different default font:
        doc.defaultStyle.font = "angsa";
        var i = 1;
    }

    //set active tab
    $("#job_tab").addClass("active");

});