$(document).ready(function () {

    function processDoc(doc) {
        //
        // https://pdfmake.github.io/docs/fonts/custom-fonts-client-side/
        //
        // Update pdfmake's global font list, using the fonts available in
        // the customized vfs_fonts.js file (do NOT remove the Roboto default):
        pdfMake.fonts = {
            Roboto: {
                normal: 'Roboto-Regular.ttf',
                bold: 'Roboto-Medium.ttf',
                italics: 'Roboto-Italic.ttf',
                bolditalics: 'Roboto-MediumItalic.ttf'
            },
            angsa: {
                normal: domain + '/fonts/angsau.ttf',
                bold: domain + '/fonts/angsaub.ttf',
                italics: domain + '/fonts/angsaui.ttf',
                bolditalics: domain + '/fonts/angsauz.ttf',
            }
        };
        // modify the PDF to use a different default font:
        doc.defaultStyle.font = "angsa";
        var i = 1;
    }



    // add color class for priority 
    function colorAdd() {
        var count = $('.table').children('tbody').children('tr:first-child').children('td').length;
        tablee = document.getElementById("patient_table");
        tr = tablee.getElementsByTagName("tr");
        // Loop through all table rows, and hide those who don't match the search query
        for (i = 1; i < tr.length; i++) {
            for (j = 0; j < count; j++) {
                td = tr[i].getElementsByTagName("td")[j];
                if (td.innerHTML.indexOf('ออกผลแล้ว') > -1) {
                    tr[i].classList.add('table-success');
                    break;
                } else if (td.innerHTML.indexOf('ด่วน') > -1) {
                    tr[i].classList.add('table-danger');
                } else {
                    //DO NOTHING
                }
            }
        }

        if (ugroup_id == '5000' || ugroup_id == '5100') {
            table.column(15).visible(false);
            table.column(17).visible(false);
        }
    }

    let hidecolumn;
    if (isCurUserCust) {
        hidecolumn = {
            visible: false,
            targets: [5, 10, 11]//, 12+1
        };
    } else {
        hidecolumn = {
            visible: false,
            targets: [5, 10]//, 12+1
        };
    }


    // datatable
    var table = $('#patient_table').DataTable({
        "ajax": "data/patient.php?skey=" + skey + "&range=2m",
        responsive: true,
        dom: 'BP<"toolbar">lfritp',

        buttons: [
            {
                text: 'export excel',
                extend: 'excel',
            },
            {
                extend: 'csv',
                text: 'export csv',
                charset: 'utf-8',
                extension: '.csv',
                fieldSeparator: ',',
                fieldBoundary: '',
                filename: 'export',
                bom: true
            },
            {
                text: 'export pdf',
                extend: 'pdf',
                customize: function (doc) {
                    processDoc(doc);
                    // Data URL generated by http://dataurl.net/#dataurlmaker
                }
            },

            {
                extend: 'collection',
                text: 'ระยะเวลาย้อนหลัง',
                autoClose: true,
                buttons: [{
                    text: '2 เดือนล่าสุด',
                    action: function (e, dt, node, config) {
                        dt.ajax.url("data/patient.php?skey=" + skey + "&range=2m").load();
                        $('#patient_title_message').text('แสดงจากข้อมูลย้อนหลัง 2 เดือน');

                    }
                },
                {
                    text: '3 เดือนล่าสุด',
                    action: function (e, dt, node, config) {
                        dt.ajax.url("data/patient.php?skey=" + skey + "&range=3m").load();
                        $('#patient_title_message').text('แสดงจากข้อมูลย้อนหลัง 3 เดือน');
                    }
                },
                {
                    text: '6 เดือนล่าสุด',
                    action: function (e, dt, node, config) {
                        dt.ajax.url("data/patient.php?skey=" + skey + "&range=6m").load();
                        $('#patient_title_message').text('แสดงจากข้อมูลย้อนหลัง 6 เดือน');
                    }
                },
                {
                    text: '1 ปีล่าสุด',
                    action: function (e, dt, node, config) {
                        dt.ajax.url("data/patient.php?skey=" + skey + "&range=1y").load();
                        $('#patient_title_message').text('แสดงจากข้อมูลย้อนหลัง 1 ปี');
                    }
                },
                {
                    text: '2 ปีล่าสุด',
                    action: function (e, dt, node, config) {
                        dt.ajax.url("data/patient.php?skey=" + skey + "&range=2y").load();
                        $('#patient_title_message').text('แสดงจากข้อมูลย้อนหลัง 2 ปี');
                    }
                },
                {
                    text: 'ทั้งหมด',
                    action: function (e, dt, node, config) {
                        dt.ajax.url("data/patient.php?skey=" + skey + "").load();
                        $('#patient_title_message').text('แสดงจากข้อมูลทั้งหมด');
                    }
                }]
            },],
        "order": [
            [0, "desc"]
        ],
        searchPanes: {
            initCollapsed: true,
        },
        columnDefs: [{
            searchPanes: {
                show: true
            },
            targets: [1, 6, 7, 8, 9, 11, 12, 13, 16, 17]//
        },
        {
            searchPanes: {
                show: false
            },
            targets: [0, 2, 3, 5, 10, 18]
        },


        //====Data header offset from display page===================================
//                    <th>#</th>                    <!-- 0 -->
//                    <th>type</th>                   <!-- 1 -->
//                    <th>เลขที่ผู้ป่วย</th>                 <!-- 2 --> 
//                    <th>HN</th>                   <!-- 3 --> 
//                    <th>ชื่อผู้ป่วย</th>                  <!-- 4 --> 
//                    <th>นามสกุลผู้ป่วย</th>             <!-- 5 -->
//                    <th>โรงพยาบาล</th>               <!-- 6 -->
//                    <th>พยาธิแพทย์</th>                <!-- 7 -->
//                    <th>วันที่รับ</th>                   <!-- 8 --> 
//                    <th>วันที่รายงาน</th>                 <!-- 9 -->
//                    <th>ใช้เวลา<br>ออกผล(วัน)</th>           <!-- 10 --> 
//                    <th>สถานะอื่นๆ</th>                 <!-- 11 -->  
//                    <th>การออกผล</th>                 <!-- 12 --> 
//                    <th>ความสำคัญ</th>                  <!-- 13 -->
//                    <th>PDF</th>                    <!-- 14 -->
//                    <th>จัดการ</th>                    <!-- 15 -->
//                    <th>แพทย์ผู้ส่ง</th>                    <!-- 16 -->
//                    <th>edit date</th>                   <!--  17 -->
//                    <th>tr</th>                          <!--  18 -->
        //=======================================================================
        //
        //=== Data offset get from data base=============
//
//                            $patient['pid']                        //0
//                            ,$patient['p_sn_type']                 //1
//                            , $patient['p_pnum']                   //2
//                            , $patient['p_phospital_num']          //3
//                            , $patient['p_pname']                  //4
//                            , $patient['p_plastname']              //5
//                            , $patient['h_hospitial']              //6
//                            , $patient['name_patho']               //7
//                            , $patient['p_date_1000']              //8
//                            , $patient['p_date_first_report']      //9
//                            , $patient['s_des']                    //10
//                            , $patient['p_reported_as']            //11
//                            , $patient['pri_priority']             //12
//                            , $patient['p_second_patho_review']    //13
//                            , $patient['p_request_sp_slide']       //14
//                            ,$patient['p_tr_time']                 //15
//                            ,$patient['p_create_by']               //16
//                            ,$patient['u_clinician']               //17
//                            ,$patient['pid']                       //18
//                            ,$patient['edit_date']                 //19
        //
        //==============================================           

        {
            "render": function (data, type, row) {
                var renderdata = '';

                if (ugroup_id == '5000' || ugroup_id == '5100') {
                    if (row[10] == "ยังไม่ออกผล") {
                        renderdata += '<p class="manage_btn_' + row[18] + ' btn btn-secondary btn-sm me-1 edit"><i class="fa-solid fa-marker"></i> Edit</p>';
                    } else {
                        renderdata += '<a href="patient_edit.php?id=' + row[18] + '&pnum=' + row[2] + '" class="manage_btn_' + row[18] + ' btn btn-outline-primary btn-sm me-1 edit"><i class="fa-solid fa-marker"></i> Edit</a>';
                    }
                }
                else {
                    renderdata += '<a href="patient_edit.php?id=' + row[18] + '&pnum=' + row[2] + '" class="manage_btn_' + row[18] + ' btn btn-outline-primary btn-sm me-1 edit"><i class="fa-solid fa-marker"></i> Edit</a>';
                    renderdata += '<a onclick="movePatient2Trash(' + row[18] + ',\'' + row[2] + '\');" class="manage_btn_' + row[18] + ' btn btn-outline-dark btn-sm"><i class="fa-solid fa-trash-can"></i> Trash</a>';

                    if (isCurUserAdmin) {
                        renderdata += '<a onclick="deletePatientPermanent(' + row[18] + ',\'' + row[2] + '\');" class="manage_btn_' + row[18] + ' btn btn-outline-dark btn-sm"><i class="fa-solid fa-eraser"></i> Delete</a>';
                    }

                }
                return renderdata;
            },
            "targets": 15
        },
        {
            "render": function (data, type, row) {
                var renderdata = '';
                // console.log("render row0 : ", row[18]);
                // setInterval(()=>{

                // }, 1000);

                if (ugroup_id == '5000' || ugroup_id == '5100') {
                    if (row[10] == "ยังไม่ออกผล") {
                        //show in-active link for customer.
                        renderdata += '<p class="btn btn-secondary btn-sm me-1 pdf"><i class="fa-solid fa-file-pdf"></i>PDF</p>';
                    } else {
                        //show active link
                        renderdata += '<a href="patient_pdf.php?id=' + row[18] + '&option=I" class="manage_pdf_' + row[18] + ' btn btn-outline-primary btn-sm me-1 pdf" target="_blank"><i class="fa fa-eye"></i>View</a>';
                        renderdata += '<a href="patient_pdf.php?id=' + row[18] + '&option=D" class="manage_pdf_' + row[18] + ' btn btn-outline-danger btn-sm me-1 pdf" target="_blank"><i class="fa-solid fa-file-pdf"></i>PDF</a>';
                        renderdata += '<a href="patient_pdf.php?id=' + row[18] + '&option=F" class="manage_pdf_' + row[18] + ' btn btn-outline-dark btn-sm me-1 pdf" target="_blank"><i class="fa fa-file-archive"></i>PDF/JPG</a>';
                    }
                }
                else {
                    //show active link

                    renderdata += '<a href="patient_pdf_for_note.php?id=' + row[18] + '&option=I" class="manage_pdf_' + row[18] + ' btn btn-outline-primary btn-sm me-1 pdf" target="_blank"><i class="fa fa-pen"></i>ใบจด</a>';
                    renderdata += '<a href="patient_pdf.php?id=' + row[18] + '&option=I" class="manage_pdf_' + row[18] + ' btn btn-outline-primary btn-sm me-1 pdf" target="_blank"><i class="fa fa-eye"></i>View</a>';
                    renderdata += '<a href="patient_pdf.php?id=' + row[18] + '&option=D" class="manage_pdf_' + row[18] + ' btn btn-outline-danger btn-sm me-1 pdf" target="_blank"><i class="fa-solid fa-file-pdf"></i>PDF</a>';
                    renderdata += '<a href="patient_pdf.php?id=' + row[18] + '&option=F" class="manage_pdf_' + row[18] + ' btn btn-outline-dark btn-sm me-1 pdf" target="_blank"><i class="fa fa-file-archive"></i>PDF/JPG</a>';
                }

                return renderdata;
            },
            "targets": (14)
        },
        {
            "render": function (data, type, row) {
                if ((ugroup_id == '5000' || ugroup_id == '5100')) {
                    if (row[10] == "ยังไม่ออกผล") {
                        //var data = '<div><h5>' + data;
                        var data = '<div><h5><a href="patient_edit.php?id=' + row[18] + '&pnum=' + row[2] + '">' + data + '</a>';
                    } else {
                        var data = '<div><h5><a href="patient_edit.php?id=' + row[18] + '&pnum=' + row[2] + '">' + data + '</a>';
                    }
                }
                else {
                    var data = '<div><h5><a href="patient_edit.php?id=' + row[18] + '&pnum=' + row[2] + '">' + data + '</a>';
                }


                if (row[12] == "ด่วน") {
                    data += ' <span class="badge bg-danger">' + row[12] + '</span>';
                }
                data += '</h5></div>';

                if (row[10] == "รับเข้า" || row[10] == "วางแผนงาน") {
                    data += '<span class="badge bg-dark">' + row[10] + '</span>';
                } else if (row[10] == "วินิจฉัย(อ่านไสลด์)") {
                    data += '<span class="badge bg-secondary">' + row[10] + '</span>';
                } else if (row[10] == "เตรียมชิ้นเนื้อ(ศัลยพยาธิ)" || row[10] == "เตรียมสไลด์(จุลพยาธิวิทยา)") {
                    data += '<span class="badge bg-info text-dark">' + row[10] + '</span>';
                } else if (row[10] == "เสร็จสิ้น") {
                    data += '<span class="badge bg-success">' + row[10] + '</span>';
                } else {
                    data += '<span class="badge bg-secondary">' + row[10] + '</span>';
                }
                return data;
            },
            "targets": (2)
        },
        {
            "render": function (data, type, row) {
                if (row[11] == "ยังไม่ออกผล") {
                    data = '<h5><span class="badge bg-secondary">' + row[11] + '</span></h5>';
                } else if (row[11] == "ออกผลเบื้องต้น") {
                    data = '<h5><span class="badge bg-info text-dark">' + row[11] + '</span></h5>';
                } else if (row[11] == "ออกผลแล้ว") {
                    data = '<h5><span class="badge bg-success">' + row[11] + '</span></h5>';
                } else {
                    data = '<h5><span class="badge bg-secondary">' + row[11] + '</span></h5>';
                }
                return data;
            },
            "targets": (12)
        },
        {
            "render": function (data, type, row) {
                return row[1];
            },
            "targets": 1
        },
        {
            "render": function (data, type, row) {
                return row[4] + ' ' + row[5];
            },
            "targets": (4)
        },
        {
            "render": function (data, type, row) {
                return row[15];
            },
            "targets": (10)
        },

        {
            "render": function (data, type, row) {
                data = '';
                data += '<small>รับเข้าโดย:</small><span class="badge bg-success">' + row[16] + '</span>';
                if (row[13] == "1") {
                    data += '<small>รอคอนเฟิร์ม:</small><span class="badge bg-warning text-dark">ร้องขอ</span><br>';
                } else if (row[13] == "2") {
                    data += '<small>รอคอนเฟิร์ม:</small><span class="badge bg-success">เสร็จสิ้น</span><br>';
                }

                if (row[14] == "1") {
                    data += '<small>ย้อมพิเศษ:</small><span class="badge bg-warning text-dark">ร้องขอ</span>';
                } else if (row[14] == "2") {
                    data += '<small>ย้อมพิเศษ:</small><span class="badge bg-success">เสร็จสิ้น</span>';
                }


                return data;
            },
            "targets": 11
        },
        {
            "render": function (data, type, row) {
                return row[12];
            },
            "targets": (13)
        },
        {
            "render": function (data, type, row) {
                return row[17];
            },
            "targets": (16)
        },
        {
            "render": function (data, type, row) {
                return row[19];
            },
            "targets": (17)
        },
        {
            "render": function (data, type, row) {
                return row[15];
            },
            "targets": (18)
        },
        // {
        //     "render": function (data, type, row) {
        //         return row[9];
        //     },
        //     "targets": (9)
        // },
        {
            responsivePriority: 0,
            targets: [4, 14, 15]
        },
        {
            responsivePriority: 1,
            targets: [2]
        },
            //        {
            //            responsivePriority: 2,
            //            targets: 2
            //        },
            //        {
            //            responsivePriority: 3,
            //            targets: -1
            //        },
            //        {
            //            responsivePriority: 10001,
            //            targets: 0
            //        },
            hidecolumn,
        {
            targets: [4, 7],
            className: 'text-nowrap'
        },
        {
            searchable: false,
            orderable: false,
            targets: 0
        }
        ],
        "initComplete": colorAdd,
    });

    table.on('order.dt search.dt', function () {
        let i = 1;

        table
            .cells(null, 0, { search: 'applied', order: 'applied' })
            .every(function (cell) {
                this.data(i++);
            });
    }).draw();


    document.querySelector('div.toolbar').innerHTML = `<div class="text-center mb-4 mt-1"><b>ซ่อนคอลัมม์ : </b>
    <a class="toggle-vis" data-column="0">#</a> -
    <a class="toggle-vis" data-column="1">type</a> -
    <a class="toggle-vis" data-column="2">เลขที่ผู้ป่วย</a> -
    <a class="toggle-vis" data-column="3">HN</a> -
    <a class="toggle-vis" data-column="4">ชื่อผู้ป่วย</a> -
    <a class="toggle-vis" data-column="6">โรงพยาบาล</a> -
    <a class="toggle-vis" data-column="7">พยาธิแพทย์</a> -
    <a class="toggle-vis" data-column="8">วันที่รับ</a> -
    <a class="toggle-vis" data-column="9">วันที่รายงาน</a> -
    <a class="toggle-vis" data-column="11">สถานะอื่นๆ</a> -
    <a class="toggle-vis" data-column="12">การออกผล</a> -
    <a class="toggle-vis" data-column="13">ความสำคัญ</a> -
    <a class="toggle-vis" data-column="16">แพทย์ผู้ส่ง</a> -
    <a class="toggle-vis" data-column="18">turn around time</a>
    <div>`;

    document.querySelectorAll('a.toggle-vis').forEach((el) => {
        el.addEventListener('click', function (e) {
            e.preventDefault();

            let columnIdx = e.target.getAttribute('data-column');
            let column = table.column(columnIdx);

            // Toggle the visibility
            column.visible(!column.visible());
        });
    });

    // add color when reload
    table.on('draw', colorAdd);


    // delete user
    $('#patient_table tbody').on('click', 'a.delete', function (e) {
        var data = table.row($(this).parents('tr')).data();

        e.preventDefault();
        if (confirm("Item will move to trash. Are you sure?")) {
            let frm = $("<form>");

            frm.attr('method', 'post');
            frm.attr('action', "patient.php");

            $('<input>', {
                type: 'hidden',
                id: 'foo',
                name: 'delete_id',
                value: data[0]
            }).appendTo(frm);

            frm.appendTo("body");
            frm.submit();
        }
    });

    // trash patient
    $('#patient_table tbody').on('click', 'a.trash', function (e) {
        var data = table.row($(this).parents('tr')).data();
        ///alert(data);

        e.preventDefault();
        if (confirm("Item will move to trash. Are you sure?")) {
            let frm = $("<form>");

            frm.attr('method', 'post');
            frm.attr('action', "patient.php");

            $('<input>', {
                type: 'hidden',
                id: 'foo',
                name: 'trash_id',
                value: data[0]
            }).appendTo(frm);

            frm.appendTo("body");
            frm.submit();


        }

    });


    // set active tab
    $("#patienttab").addClass("active");


});



function movePatient2Trash(patient_id, patient_num) {
    //e.preventDefault();
    if (confirm("Item " + patient_num + " will move to trash. Are you sure?")) {
        $.ajax({
            'async': false,
            type: 'POST',
            'global': false,
            type: 'POST',
            url: 'ajax_patient/move2trash.php',
            data: {
                'id': patient_id,
                'patient_num': patient_num,
            },
            success: function (data) {
                console.log(data);
                if (confirm("Item " + patient_num + " was deleted.\nDo you want to refresh this page to see result?")) {
                    location.reload();
                } else {
                    let tgt_manage_btn = '.manage_btn_' + patient_id;
                    let tgt_pdf_btn = '.manage_pdf_' + patient_id;
                    $(tgt_manage_btn).addClass('disabled');
                    $(tgt_pdf_btn).addClass('disabled');
                }
            },
            error: function (jqxhr, status, exception) {
                alert('Exception:', exception);
            }
        });
    }
}




function deletePatientPermanent(patient_id, patient_num) {
    //e.preventDefault();
    if (confirm("Item " + patient_num + " will be delete permanent. Are you sure?")) {
        $.ajax({
            'async': false,
            type: 'POST',
            'global': false,
            type: 'POST',
            url: 'ajax_patient/deletePatient.php',
            data: {
                'id': patient_id,
                'patient_num': patient_num,
            },
            success: function (data) {
                data = data.trim();
                console.log('"' + data + '"');
                console.log(typeof data)
                //The localeCompare() method returns sort order -1, 1, or 0 (for before, after, or equal).
                if (data.localeCompare("1") != 0) { // if execute fail
                    alert(data);
                    return false;
                }

                if (confirm("Item " + patient_num + " was deleted.\nDo you want to refresh this page to see result?")) {
                    location.reload();
                } else {
                    let tgt_manage_btn = '.manage_btn_' + patient_id;
                    let tgt_pdf_btn = '.manage_pdf_' + patient_id;
                    $(tgt_manage_btn).addClass('disabled');
                    $(tgt_pdf_btn).addClass('disabled');
                }
            },
            error: function (jqxhr, status, exception) {
                alert('Exception:', exception);
            }
        });
    }

}