$(document).ready(function () {

    function processDoc(doc) {
        //
        // https://pdfmake.github.io/docs/fonts/custom-fonts-client-side/
        //
        // Update pdfmake's global font list, using the fonts available in
        // the customized vfs_fonts.js file (do NOT remove the Roboto default):
        pdfMake.fonts = {
            Roboto: {
                normal: 'Roboto-Regular.ttf',
                bold: 'Roboto-Medium.ttf',
                italics: 'Roboto-Italic.ttf',
                bolditalics: 'Roboto-MediumItalic.ttf'
            },
            angsa : {
                normal: domain+'/fonts/angsau.ttf',
                bold: domain+'/fonts/angsaub.ttf',
                italics: domain+'/fonts/angsaui.ttf',
                bolditalics: domain+'/fonts/angsauz.ttf',
            }
        };
        // modify the PDF to use a different default font:
        doc.defaultStyle.font = "angsa";
        var i = 1;
    }



    // add color class for priority 
    function colorAdd() {
        var count = $('.table').children('tbody').children('tr:first-child').children('td').length;
        tablee = document.getElementById("patient_table");
        tr = tablee.getElementsByTagName("tr");
        // Loop through all table rows, and hide those who don't match the search query
        for (i = 1; i < tr.length; i++) {
            for (j = 0; j < count; j++) {
                td = tr[i].getElementsByTagName("td")[j];
                if (td.innerHTML.indexOf('ออกผลแล้ว') > -1) {
                    tr[i].classList.add('table-success');
                    break;
                } else if (td.innerHTML.indexOf('ด่วน') > -1) {
                    tr[i].classList.add('table-danger');
                } else {
                    //DO NOTHING
                }
            }
        }

        if (ugroup_id == '5000' || ugroup_id == '5100') {
            table.column(14).visible(false);
        }


    }

    let hidecolumn;
    if (isCurUserCust) {
        hidecolumn = {
            visible: false,
            targets: [ 4, 10, 12]
        };
    } else {
        hidecolumn = {
            visible: false,
            targets: [ 4, 12]
        };
    }


    // datatable
    var table = $('#patient_table').DataTable({
        "ajax": "data/patient.php?skey=" + skey + "&range=1m",
        responsive: true,
        dom: 'BPlfrtip',
        
        buttons: [
            {
                text: 'export excel',
                extend: 'excel',
            },
            {
                extend: 'csv',
                text: 'export csv',
                charset: 'utf-8',
                extension: '.csv',
                fieldSeparator: ',',
                fieldBoundary: '',
                filename: 'export',
                bom: true
            },
            {
                text: 'export pdf',
                extend: 'pdf',
                customize: function (doc) {
                    processDoc(doc);
                    // Data URL generated by http://dataurl.net/#dataurlmaker
                }
            },
            
            {
            extend: 'collection',
            text: 'ระยะเวลาย้อนหลัง',
            autoClose: true,
            buttons: [{
                text: '1 เดือนล่าสุด',
                action: function (e, dt, node, config) {
                    dt.ajax.url("data/patient.php?skey=" + skey + "&range=1m").load();
                    $('#patient_title_message').text('แสดงจากข้อมูลย้อนหลัง 1 เดือน');

                }
            },
            {
                text: '3 เดือนล่าสุด',
                action: function (e, dt, node, config) {
                    dt.ajax.url("data/patient.php?skey=" + skey + "&range=3m").load();
                    $('#patient_title_message').text('แสดงจากข้อมูลย้อนหลัง 3 เดือน');
                }
            },
            {
                text: '6 เดือนล่าสุด',
                action: function (e, dt, node, config) {
                    dt.ajax.url("data/patient.php?skey=" + skey + "&range=6m").load();
                    $('#patient_title_message').text('แสดงจากข้อมูลย้อนหลัง 6 เดือน');
                }
            },
            {
                text: '1 ปีล่าสุด',
                action: function (e, dt, node, config) {
                    dt.ajax.url("data/patient.php?skey=" + skey + "&range=1y").load();
                    $('#patient_title_message').text('แสดงจากข้อมูลย้อนหลัง 1 ปี');
                }
            },
            {
                text: '2 ปีล่าสุด',
                action: function (e, dt, node, config) {
                    dt.ajax.url("data/patient.php?skey=" + skey + "&range=2y").load();
                    $('#patient_title_message').text('แสดงจากข้อมูลย้อนหลัง 2 ปี');
                }
            },
            {
                text: 'ทั้งหมด',
                action: function (e, dt, node, config) {
                    dt.ajax.url("data/patient.php?skey=" + skey + "").load();
                    $('#patient_title_message').text('แสดงจากข้อมูลทั้งหมด');
                }
            }
            ]
        },],
        "order": [
            [0, "desc"]
        ],
        searchPanes: {
            initCollapsed: true,
        },
        columnDefs: [{
            searchPanes: {
                show: true
            },
            targets: [5, 6, 7, 8, 10, 11, 12]
        },
        {
            searchPanes: {
                show: false
            },
            targets: [0, 1, 2, 4]
        },
        
//====Data header offset from display page===================================
//                    <th>#</th>                    <!-- 0 -->
//                    <th>เลขที่ผู้ป่วย</th>              <!-- 1 -->
//                    <th>HN</th>                     <!-- 2 -->
//                    <th>ชื่อผู้ป่วย</th>                    <!-- 3 --> 
//                    <th>นามสกุลผู้ป่วย</th>                 <!-- 4 -->
//                    <th>โรงพยาบาล</th>                  <!-- 5 -->
//                    <th>พยาธิแพทย์</th>                 <!-- 6 -->
//                    <th>วันที่รับ</th>                     <!-- 7 -->
//                    <th>วันที่รายงาน</th>                <!-- 8 -->
//                    <th>tr_time</th>                <!-- 9 -->
//                    <th>สถานะอื่นๆ</th>                  <!-- 10 -->
//                    <th>การออกผล</th>                   <!-- 11 --> 
//                    <th>ความสำคัญ</th>                <!-- 12 -->
//                    <th>PDF</th>                    <!-- 13 -->
//                    <th>จัดการ</th>                    <!-- 14 -->
//=======================================================================
//
//=== Data offset get from data base=============
//   $data[] = [$patient['pid'], $patient['pnum'], $patient['phospital_num'], $patient['pname'], $patient['plastname'], $patient['hospital'], 
//-------------------------0----------------1-----------------2-----------------------3---------------------4-------------------5----------
//
//$patient['name'], $patient['date_1000'], $patient['date_20000'], $patient['des'], $patient['reported_as'],
//----------6-----------------------7--------------------8-------------------9--------------------10--------
//
// $patient['priority'], $patient['second_patho_review'], $patient['request_sp_slide'],$patient['tr_time'],$patient['pcreate_by']];
//-----------------11------------------------------12-----------------------13--------------------14------------------15-------
//
//==============================================           
            
        {
            "render": function (data, type, row) {
                var renderdata = '';

                if (ugroup_id == '5000' || ugroup_id == '5100') {
                    if (row[9] == "ยังไม่ออกผล") {
                        renderdata += '<p class="manage_btn_'+row[0]+' btn btn-secondary btn-sm me-1 edit"><i class="fa-solid fa-marker"></i> Edit</p>';
                    } else {
                        renderdata += '<a href="patient_edit.php?id=' + row[0] + '&pnum=' + row[1] + '" class="manage_btn_'+row[0]+' btn btn-outline-primary btn-sm me-1 edit"><i class="fa-solid fa-marker"></i> Edit</a>';
                    }
                }
                else {
                    renderdata += '<a href="patient_edit.php?id=' + row[0] + '&pnum=' + row[1] + '" class="manage_btn_'+row[0]+' btn btn-outline-primary btn-sm me-1 edit"><i class="fa-solid fa-marker"></i> Edit</a>';
                    renderdata += '<a onclick="movePatient2Trash('+row[0]+',\''+row[1]+'\');" class="manage_btn_'+row[0]+' btn btn-outline-dark btn-sm"><i class="fa-solid fa-trash-can"></i> Trash</a>';

                    if (isCurUserAdmin) {
                        renderdata += '<a href="patient_del.php?id=' + row[0] + '&pnum=' + row[1] + '" class="manage_btn_'+row[0]+' btn btn-outline-dark btn-sm delete"><i class="fa-solid fa-trash-can"></i> Delete</a>';
                    }

                }
                return renderdata;
            },
            "targets": -1
        },
        {
            "render": function (data, type, row) {
                var renderdata = '';

                if (ugroup_id == '5000' || ugroup_id == '5100') {
                    if (row[9] == "ยังไม่ออกผล") {
                        //show in-active link for customer.
                        renderdata += '<p class="btn btn-secondary btn-sm me-1 pdf"><i class="fa-solid fa-file-pdf"></i>PDF</p>';
                    } else {
                        //show active link
                        renderdata += '<a href="patient_pdf.php?id=' + row[0] + '&option=I" class="manage_pdf_'+row[0]+' btn btn-outline-primary btn-sm me-1 pdf" target="_blank"><i class="fa fa-eye"></i>View</a>';
                        renderdata += '<a href="patient_pdf.php?id=' + row[0] + '&option=D" class="manage_pdf_'+row[0]+' btn btn-outline-danger btn-sm me-1 pdf" target="_blank"><i class="fa-solid fa-file-pdf"></i>PDF</a>';
                        renderdata += '<a href="patient_pdf.php?id=' + row[0] + '&option=F" class="manage_pdf_'+row[0]+' btn btn-outline-secondary btn-sm me-1 pdf" target="_blank"><i class="fa fa-file-archive"></i>PDF/JPG</a>';                    }
                }
                else {
                    //show active link
                    renderdata += '<a href="patient_pdf.php?id=' + row[0] + '&option=I" class="manage_pdf_'+row[0]+' btn btn-outline-primary btn-sm me-1 pdf" target="_blank"><i class="fa fa-eye"></i>View</a>';
                    renderdata += '<a href="patient_pdf.php?id=' + row[0] + '&option=D" class="manage_pdf_'+row[0]+' btn btn-outline-danger btn-sm me-1 pdf" target="_blank"><i class="fa-solid fa-file-pdf"></i>PDF</a>';
                    renderdata += '<a href="patient_pdf.php?id=' + row[0] + '&option=F" class="manage_pdf_'+row[0]+' btn btn-outline-secondary btn-sm me-1 pdf" target="_blank"><i class="fa fa-file-archive"></i>PDF/JPG</a>';
                }

                return renderdata;
            },
            "targets": 13
        },
        {
            "render": function (data, type, row) {
                if ((ugroup_id == '5000' || ugroup_id == '5100')) {
                    if (row[9] == "ยังไม่ออกผล") {
                        //var data = '<div><h5>' + data;
                        var data = '<div><h5><a href="patient_edit.php?id=' + row[0] + '&pnum=' + row[1] + '">' + data + '</a>';
                    } else {
                        var data = '<div><h5><a href="patient_edit.php?id=' + row[0] + '&pnum=' + row[1] + '">' + data + '</a>';
                    }
                }
                else {
                    var data = '<div><h5><a href="patient_edit.php?id=' + row[0] + '&pnum=' + row[1] + '">' + data + '</a>';
                }


                if (row[11] == "ด่วน") {
                    data += ' <span class="badge bg-danger">' + row[11] + '</span>';
                }
                data += '</h5></div>';

                if (row[9] == "รับเข้า" || row[9] == "วางแผนงาน") {
                    data += '<span class="badge bg-dark">' + row[9] + '</span>';
                } else if (row[9] == "วินิจฉัย(อ่านไสลด์)") {
                    data += '<span class="badge bg-secondary">' + row[9] + '</span>';
                } else if (row[9] == "เตรียมชิ้นเนื้อ(ศัลยพยาธิ)" || row[9] == "เตรียมสไลด์(จุลพยาธิวิทยา)") {
                    data += '<span class="badge bg-info text-dark">' + row[9] + '</span>';
                } else if (row[9] == "เสร็จสิ้น") {
                    data += '<span class="badge bg-success">' + row[9] + '</span>';
                } else {
                    data += '<span class="badge bg-secondary">' + row[9] + '</span>';
                }
                return data;
            },
            "targets": 1
        },
        {
            "render": function (data, type, row) {
                if (row[10] == "ยังไม่ออกผล") {
                    data = '<h5><span class="badge bg-secondary">' + row[10] + '</span></h5>';
                } else if (row[10] == "ออกผลเบื้องต้น") {
                    data = '<h5><span class="badge bg-info text-dark">' + row[10] + '</span></h5>';
                } else if (row[10] == "ออกผลแล้ว") {
                    data = '<h5><span class="badge bg-success">' + row[10] + '</span></h5>';
                } else {
                    data = '<h5><span class="badge bg-secondary">' + row[10] + '</span></h5>';
                }
                return data;
            },
            "targets": 11
        },
        {
            "render": function (data, type, row) {
                return row[3] + '<br>' + row[4];
            },
            "targets": 3
        },
        {
            "render": function (data, type, row) {
                return row[14];
            },
            "targets": 9
        },
        {
            "render": function (data, type, row) {
                data = '';
                data += '<small>รับเข้าโดย:</small><span class="badge bg-success">'+row[15]+'</span>';
                if (row[12] == "1") {
                    data += '<small>รอคอนเฟิร์ม:</small><span class="badge bg-warning text-dark">ร้องขอ</span><br>';
                } else if (row[12] == "2") {
                    data += '<small>รอคอนเฟิร์ม:</small><span class="badge bg-success">เสร็จสิ้น</span><br>';
                }

                if (row[13] == "1") {
                    data += '<small>ย้อมพิเศษ:</small><span class="badge bg-warning text-dark">ร้องขอ</span>';
                } else if (row[13] == "2") {
                    data += '<small>ย้อมพิเศษ:</small><span class="badge bg-success">เสร็จสิ้น</span>';
                }

//                for (i = 0; i < row.length; i++) {
//                    data += '<small>row[' + i + ']:</small><span class="badge bg-success">' + row[i] + '</span>';
//                }


                return data;
            },
            "targets": 10
        },
        {
            responsivePriority: 0,
            targets: 0
        },
//        {
//            responsivePriority: 1,
//            targets: 1
//        },
//        {
//            responsivePriority: 2,
//            targets: 2
//        },
//        {
//            responsivePriority: 3,
//            targets: -1
//        },
//        {
//            responsivePriority: 10001,
//            targets: 0
//        },
            hidecolumn,
        ],
        "initComplete": colorAdd,
    });

    // add color when reload
    table.on('draw', colorAdd);


    // delete user
    $('#patient_table tbody').on('click', 'a.delete', function (e) {
        var data = table.row($(this).parents('tr')).data();

        e.preventDefault();
        if (confirm("Item will move to trash. Are you sure?")) {
            let frm = $("<form>");

            frm.attr('method', 'post');
            frm.attr('action', "patient.php");

            $('<input>', {
                type: 'hidden',
                id: 'foo',
                name: 'delete_id',
                value: data[0]
            }).appendTo(frm);

            frm.appendTo("body");
            frm.submit();
        }
    });

    // trash patient
    $('#patient_table tbody').on('click', 'a.trash', function (e) {
        var data = table.row($(this).parents('tr')).data();
        ///alert(data);

        e.preventDefault();
        if (confirm("Item will move to trash. Are you sure?")) {
            let frm = $("<form>");

            frm.attr('method', 'post');
            frm.attr('action', "patient.php");

            $('<input>', {
                type: 'hidden',
                id: 'foo',
                name: 'trash_id',
                value: data[0]
            }).appendTo(frm);

            frm.appendTo("body");
            frm.submit();


        }

    });
    

    // set active tab
    $("#patienttab").addClass("active");
    

});

function movePatient2Trash(patient_id, patient_num){
    //e.preventDefault();
    if (confirm("Item "+patient_num+" will move to trash. Are you sure?")) {
            $.ajax({
            'async': false,
            type: 'POST',
            'global': false,
            type: 'POST',
            url: 'ajax_patient/move2trash.php',
            data: {
                'id': patient_id
            },
            success: function (data) {
                console.log(data);
                if (confirm("Item " + patient_num + " was deleted.\nDo you want to refresh this page to see result?")) {
                    location.reload();
                }else{
                    let tgt_manage_btn = '.manage_btn_'+patient_id;
                    let tgt_pdf_btn = '.manage_pdf_'+patient_id;
                    $(tgt_manage_btn).addClass('disabled');
                    $(tgt_pdf_btn).addClass('disabled');
                }
            },
            error: function (jqxhr, status, exception) {
                alert('Exception:', exception);
            }
        });
         

    }

    
}
