$(document).ready(function () {

    function processDoc(doc) {
        //
        // https://pdfmake.github.io/docs/fonts/custom-fonts-client-side/
        //
        // Update pdfmake's global font list, using the fonts available in
        // the customized vfs_fonts.js file (do NOT remove the Roboto default):
        pdfMake.fonts = {
            Roboto: {
                normal: 'Roboto-Regular.ttf',
                bold: 'Roboto-Medium.ttf',
                italics: 'Roboto-Italic.ttf',
                bolditalics: 'Roboto-MediumItalic.ttf'
            },
            angsa: {
                normal: domain + '/fonts/angsau.ttf',
                bold: domain + '/fonts/angsaub.ttf',
                italics: domain + '/fonts/angsaui.ttf',
                bolditalics: domain + '/fonts/angsauz.ttf',
            }
        };
        // modify the PDF to use a different default font:
        doc.defaultStyle.font = "angsa";
        var i = 1;
    }

    // datatable
    var table = $('#request_sp_sl_table').DataTable({
        "ajax": "data/patientSpSlReq.php?skey=" + skey + "&range=3m",
        responsive: true,
        dom: 'PlfBrtip',
        // searchPanes: {
        //     dtOpts: {
        //         order: [[5, 'desc']]
        //     }
        // },
        buttons: [
            {
                text: 'export excel',
                extend: 'excel',
            },
            {
                extend: 'csv',
                text: 'export csv',
                charset: 'utf-8',
                extension: '.csv',
                fieldSeparator: ',',
                fieldBoundary: '',
                filename: 'export',
                bom: true
            },
            {
                text: 'export pdf',
                extend: 'pdf',
                customize: function (doc) {
                    processDoc(doc);
                    // Data URL generated by http://dataurl.net/#dataurlmaker
                }
            },
            {
                extend: 'collection',
                text: 'ระยะเวลาย้อนหลัง',
                autoClose: true,
                buttons: [{
                    text: '1 เดือนล่าสุด',
                    action: function (e, dt, node, config) {
                        dt.ajax.url("data/patientSpSlReq.php?skey=" + skey + "&range=1m").load();
                    }
                },
                {
                    text: '3 เดือนล่าสุด',
                    action: function (e, dt, node, config) {
                        dt.ajax.url("data/patientSpSlReq.php?skey=" + skey + "&range=3m").load();
                    }
                },
                {
                    text: '6 เดือนล่าสุด',
                    action: function (e, dt, node, config) {
                        dt.ajax.url("data/patientSpSlReq.php?skey=" + skey + "&range=6m").load();
                    }
                },
                {
                    text: '1 ปีล่าสุด',
                    action: function (e, dt, node, config) {
                        dt.ajax.url("data/patientSpSlReq.php?skey=" + skey + "&range=1y").load();
                    }
                },
                {
                    text: '2 ปีล่าสุด',
                    action: function (e, dt, node, config) {
                        dt.ajax.url("data/patientSpSlReq.php?skey=" + skey + "&range=2y").load();
                    }
                },
                {
                    text: 'ทั้งหมด',
                    action: function (e, dt, node, config) {
                        dt.ajax.url("data/patientSpSlReq.php?skey=" + skey + "").load();
                    }
                }
                ]
            },],
        "order": [
            [0, "desc"]
        ],
        "searchPanes":  {
            initCollapsed: true,
            dtOpts: {
              order: [[ 0, "desc" ]]
            }                                 
          },
        columnDefs: [{
            searchPanes: {
                show: true
            },
            targets: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,12]
        },
        {
            searchPanes: {
                show: false
            },
            targets: [0]
        },
        {
            searchPanes: {
                "order": [
                    [5, "desc"]
                ],
            },
        },

        {
            "render": function (data, type, row) {
                let renderdata = '';
                if (row[6]) {
                    //If finish date is avalable
                    renderdata += '<a class="btn btn-success btn-sm  rid' + row[0] + ' " disabled><i class="fa-sharp fa-solid fa-check"></i> <span class="btn_msg_' + row[0] + '">FINISHED</span> rid' + row[0] + ' </a>';
                } else {
                    //If finished date is null
                    renderdata += '<a onclick="doneTheJobSP(' + row[0] + ')"  class="btn btn-warning btn-sm done  rid' + row[0] + '"><i class="fa-sharp fa-solid fa-check "></i> <span class="btn_msg_' + row[0] + '">CLOSE</span> rid' + row[0] + ' </a>';
                }
                return renderdata;
            },
            "targets": -1
        },
        {
            responsivePriority: 1,
            targets: 1
        },
        {
            responsivePriority: 2,
            targets: 2
        },
        {
            responsivePriority: 3,
            targets: -1
        },
        {
            responsivePriority: 10001,
            targets: 0
        },
        {
            visible: true,
             targets: [0, 4, 5, 6, 7, 8, 9, 10, 11,12]
        },
        {
            visible: false,
            targets: [1, 2, 3]
        },
        ],
        //        "initComplete": colorAdd,
    });

    // add color when reload
    //    table.on('draw', colorAdd);

    //        table.on('draw', function() {
    //            // console.log(table.rows().data());
    //            rawdata = table.rows().data();
    //            console.log(rawdata);
    //            alert("rawdata print");
    //        });




    // set active tab
    $("#patienttab_8000").addClass("active");

    //    setInterval( function () {
    //        table.ajax.reload( null, false ); // user paging is not reset on reload
    //    }, 10000 );

});

function doneTheJobSP(rid) {


    let setDate;
    $.ajax({
        type: 'POST',
        async: false,
        url: 'ajax_job4_prep_sp_slide/set_finish_date_sp_slide.php',
        data: {
            'rid': rid,
        },
        success: function (data) {
            //            alert(data);
            setDate = data;
        },
        error: function (jqxhr, status, exception) {
            alert('Exception:', exception);
        }

    });


    let classRIDName = '.rid' + rid;
    $(classRIDName).addClass('disabled');
    $(classRIDName).removeClass("btn-warning").addClass("btn-success");
    alert("Done, set finished to " + setDate);

}

//on click button delete for seleced specimen list bill in main page
function deljob1x(jobid, patientid) {

    if (confirm("Please confirm delete job di = " + jobid + " ?")) {

        $.ajax({
            type: 'POST',
            // make sure you respect the same origin policy with this url:
            // http://en.wikipedia.org/wiki/Same_origin_policy
            url: 'ajax_job1_crossection/delJob1.php',
            data: {
                'job_id': jobid,
                'patient_id': patientid,

            },
            success: function (data) {

                repaintTbljob1(data);

                alert('Success');
            },
            error: function (jqxhr, status, exception) {
                alert('Exception:', exception);
            }

        });

    } else {

    }

}