<?php
require 'includes/init.php';
// var_dump($_SESSION['user']->id);exit;
// Auth::requireLogin();
Auth::requireLogin("user_sim_admin.php");

$conn = require 'includes/db.php';
require 'user_auth.php';





//$ugroups = Ugroup::getAll($conn);
//$hospitals = Hospital::getAll($conn);
//var_dump($hospitals);




if (isset($_GET['id'])) {
    if ($isCurUserAdmin) {
        Auth::adminSimulatelogin($conn, $_GET['id']);
        Url::redirect('/login.php');
    }
}
?>
<?php // require 'includes/data2DOM.php';   ?>

<?php require 'includes/header.php'; ?>



<div class="container-fluid pt-4 px-4">
    <div class="row bg-nb bg-blue-a rounded align-items-center justify-content-center p-3 mx-1">


        <div class="d-flex align-items-center justify-content-between">

        </div>

    </div>
</div>

<div class="container-fluid pt-4 px-4">
    <div class="row bg-nb bg-blue-a rounded align-items-center justify-content-center p-3 mx-1">

        <table class="table table-hover table-striped text-center" id="DataTableID" style="width:100%">
            <thead>
                <tr>
                </tr>
            </thead>

        </table>



    </div>
</div>




<?php require 'includes/footer.php'; ?>
<script type="text/javascript">
    var skey = '<?= $_SESSION["skey"]; ?>';

    var datefrom = $("#startdate_billing").val();
    var dateto = $("#enddate_billing").val();

    $(document).ready(function () {
        function processDoc(doc) {
            //
            // https://pdfmake.github.io/docs/fonts/custom-fonts-client-side/
            //
            // Update pdfmake's global font list, using the fonts available in
            // the customized vfs_fonts.js file (do NOT remove the Roboto default):
            pdfMake.fonts = {
                Roboto: {
                    normal: 'Roboto-Regular.ttf',
                    bold: 'Roboto-Medium.ttf',
                    italics: 'Roboto-Italic.ttf',
                    bolditalics: 'Roboto-MediumItalic.ttf'
                },
                angsa: {
                    normal: domain + '/fonts/angsau.ttf',
                    bold: domain + '/fonts/angsaub.ttf',
                    italics: domain + '/fonts/angsaui.ttf',
                    bolditalics: domain + '/fonts/angsauz.ttf',
                }
            };
            // modify the PDF to use a different default font:
            doc.defaultStyle.font = "angsa";
            var i = 1;
        }


        // table data
        var table = $('#DataTableID').DataTable({
            columns: [
                {title: 'name'},
                {title: 'surname'},
                {title: 'SN'},
                {title: 'age'},
                {title: 'hn'},
                {title: 'Hospital'},
                {title: 'Specimen'},
                {title: 'ssource'},
                {title: 'specimen_adequacy'},
                {title: 'interpretation'},
                {title: 'EDUCATIONAL_NOTES_AND_SUGGESTION'},
                {title: 'Date_Received'},
                {title: 'Date_Report'},
                {title: 'Pathologist'},
                {title: 'Cytologist'}
            ],

            "ajax": "data/datatable_patient_pn_rev1_ajax.php?skey=" + skey + "&datefrom=" + $,
            responsive: true,
            dom: 'BP<"toolbar">lfritip',
            pageLength: 100,
            buttons: [
                {
                    text: 'export excel',
                    extend: 'excel',
                },
                {
                    extend: 'csv',
                    text: 'export csv',
                    charset: 'utf-8',
                    extension: '.csv',
                    fieldSeparator: ',',
                    fieldBoundary: '',
                    filename: 'export',
                    bom: true
                },
                {
                    text: 'export pdf',
                    extend: 'pdf',
                    customize: function (doc) {
                        processDoc(doc);
                        // Data URL generated by http://dataurl.net/#dataurlmaker
                    }
                },

                {
                    extend: 'collection',
                    text: 'ระยะเวลาย้อนหลัง',
                    autoClose: true,
                    buttons: [{
                            text: '2 เดือนล่าสุด',
                            action: function (e, dt, node, config) {
                                dt.ajax.url("data/datatable_patient_pn_rev1_ajax.php?skey=" + skey + "&range=2m").load();
                                $('#BTN_SELECTION_MESSAGE').text('แสดงจากข้อมูลย้อนหลัง 2 เดือน');

                            }
                        },
                        {
                            text: '3 เดือนล่าสุด',
                            action: function (e, dt, node, config) {
                                dt.ajax.url("data/datatable_patient_pn_rev1_ajax.php?skey=" + skey + "&range=3m").load();
                                $('#BTN_SELECTION_MESSAGE').text('แสดงจากข้อมูลย้อนหลัง 3 เดือน');
                            }
                        },
                        {
                            text: '6 เดือนล่าสุด',
                            action: function (e, dt, node, config) {
                                dt.ajax.url("data/datatable_patient_pn_rev1_ajax.php?skey=" + skey + "&range=6m").load();
                                $('#BTN_SELECTION_MESSAGE').text('แสดงจากข้อมูลย้อนหลัง 6 เดือน');
                            }
                        },
                        {
                            text: '1 ปีล่าสุด',
                            action: function (e, dt, node, config) {
                                dt.ajax.url("data/datatable_patient_pn_rev1_ajax.php?skey=" + skey + "&range=1y").load();
                                $('#BTN_SELECTION_MESSAGE').text('แสดงจากข้อมูลย้อนหลัง 1 ปี');
                            }
                        },
                        {
                            text: '2 ปีล่าสุด',
                            action: function (e, dt, node, config) {
                                dt.ajax.url("data/datatable_patient_pn_rev1_ajax.php?skey=" + skey + "&range=2y").load();
                                $('#BTN_SELECTION_MESSAGE').text('แสดงจากข้อมูลย้อนหลัง 2 ปี');
                            }
                        },
                        {
                            text: 'ทั้งหมด',
                            action: function (e, dt, node, config) {
                                dt.ajax.url("data/datatable_patient_pn_rev1_ajax.php?skey=" + skey + "").load();
                                $('#BTN_SELECTION_MESSAGE').text('แสดงจากข้อมูลทั้งหมด');
                            }
                        }]
                }, ],
            searchPanes: {
                initCollapsed: true,
                // cascadePanes: true,
            },
            columnDefs: [{
                    searchPanes: {
                        show: true
                    },
                    targets: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
                },
                {
                    searchPanes: {
                        show: false
                    },
                    targets: []
                },

                {
                    "render": function (data, type, row) {
                        //example link page
                        data = row[1];
                        return data;
                    },
                    "targets": 1
                },
                {
                    "render": function (data, type, row) {

                        data = row[3];
                        return data;
                    },
                    "targets": 3
                },
               
                {
                    visible: false,
                    targets: []
                },
            ]
        });

        // delete user
//        $('#DataTableID tbody').on('click', 'a.delete', function(e) {
//            var data = table.row($(this).parents('tr')).data();
//
//            e.preventDefault();
//            if (confirm("Are you sure?")) {
//                var frm = $("<form>");
//                frm.attr('method', 'post');
//                frm.attr('action', "user_del.php?id=" + data[0]);
//                frm.appendTo("body");
//                frm.submit();
//            }
//        });


        // set active tab
        $("#SIDE_tab").addClass("active");
        $("#SUBSIDEBAR_tab").addClass("active");
    });
</script>